# Data Analysis on Salary Data


### About DataSet : 

#### There is one company uploaded their DataSet . They provided us Salary according to the YearsExperience in their DataSet. 

### Step 1 :- Uploading Dataset 

In [31]:
## Importing pandas module 

import pandas

In [32]:
## Used read_csv( ) function to upload or read the DataSet i,e Salary_Data.csv

DataSet= pandas.read_csv("Salary_Data.csv")

In [33]:
## Printing to see the Data of the DataSet

DataSet

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

## Step 2 :- Data preparation

#### Note :- No need to find out the Correlations here because there is a single Independent Varible .

In [34]:
## Here , YearsExperience is an independent column , Storing the data of this column in a varible i.e x 
## Usually , we use x varible to store the data of Independent Column 



x = DataSet["YearsExperience"] 

In [35]:
## Here , Salary is a Dependent column , Storing the data of this column in a varible i.e y
## Usually , we use y varible to store the data of Dependent Column 

y = DataSet["Salary"]  

In [36]:
x 



0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [37]:
y # printing the data of Salary


0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [38]:
## Using shape attribute to see the Shape/Size/No.of elements/Dimension of YearsExperience colomn what stored in x varible 

x.shape   

## Here , By default Dimension will be 1D 
## No .of Elements = 30


(30,)

In [39]:
## values attribute to see how many values are there in a particle column along with to see the all the values 
## Output will be in a Array

x.values  

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [40]:
## use reshape function to reshape meaning that to change the dimention of any array , here using this technique to convert 1D to 2D
## We will use fit function to trend our Machine , there will be require 2D Array Data Items that's why converting here

X = x.values.reshape(-1,1) 
                          

In [41]:
## Now , Check the Dimension of X 
X.shape

## Output will be in 2D

(30, 1)

In [42]:
y.values

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

## Step 3 :- Data Wrangling

#### Missing Values , Duplicate data , Invalid data and Noise , no need here .

## Step 4 :- Data Analysis 


In [43]:
## Here , the values of y is continuous meaning that it is a linear and there is only one independent varible . 
## This Type of Problem can solve or analyze with the help of Simple Linear Regression . 

## Simple      = Only one Independent Variable.  
## Linear      = The values of y is continuous and increasing continuously , you can see with the help of plot .
## Regression  = The values of y is not fixed , it may be anything. 

In [44]:
# LinearRegression, This is a subclass of Parent Class i.e Linear_model, we use to solve any Simple Linear Regreesion Problem .
# linear_model , this is parent class of LinearRegression .  
# sklearn , This is one module , Linear_model Class belongs from this module .

In [45]:
from sklearn.linear_model import LinearRegression #Importing LR SubClass using Import Keyword

In [46]:
# Create a object using LinearRegression() 

model = LinearRegression() 

In [47]:
model

LinearRegression()

In [48]:
# To see the function and keyword what are available inside this model as a object/namespace

dir(model)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_n_features',
 '_decision_function',
 '_estimator_type',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_preprocess_data',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_intercept',
 '_validate_data',
 'copy_X',
 'fit',
 'fit_intercept',
 'get_params',
 'n_jobs',
 'normalize',
 'positive',
 'predict',
 'score',
 'set_params']

## Step 5 : Train Model 

In [49]:
## Add x and y i.e (x,y) in this order or else model will be created in reverse order. 
## This function need the value of x in 2D. 

##Using this fit function we trained our machine and find the complete model/formula meaning that
##find the value of W means Weight/Cofficient/Slope and Bais i.e B

## LinearRegression Behind the scene use Y = B + WX 

## Y = Input Data
## B = Bias
## W = Weight
## X = Output (Prediction/Outcomes)



model.fit(X,y) 

LinearRegression()

## Step 6:- Test Model

In [50]:
## Passing the value 1.4 as a Input i. e the value of X to predict the value of y 

model.predict([[1.4]]) 

array([39022.14744871])

In [51]:
##coef_ attribute  , To see the Cofficient/Weight of your Model

model.coef_ 

array([9449.96232146])

In [52]:
## intercept_ attribute , to see the Bias/Intercept of your Model

model.intercept_ 

25792.20019866871

In [53]:
## x = 1.4 
## w = 9449
## b = 25792

## Y = b + wx , this is a linear equation formula , LR use behind the scene

y = 25792 +(9449*1.4)

In [54]:
y

39020.6

In [43]:
## If you know the value of W and Bais then you can easily find the value of Y .
## Main Goal of ML is to find Bias and Weight . 

In [ ]:
## Error = Y real value - Y prediction value 